site_name: Tech Notes
copyright: Copyright &copy; 2020 Nan Lei
site_description: Tech Notes
repo_url: https://github.com/nanlei/my-notes
site_author : Nan Lei

nav:
  - Home: index.md
  - Framework:
    - Spring Boot:
      - 'Standalone Application' : 'SpringBoot/01-spring-boot-application.md'
      - 'Maven Dependencies' : 'SpringBoot/02-spring-boot-maven-dependency.md'
      - 'Embedded Web Server' : 'SpringBoot/03-spring-boot-embedded-web-server.md'
      - 'Understanding Auto-Configuration' : 'SpringBoot/04-spring-boot-understanding-auto-config.md'
  - DataBase:
    - MySQL:
      - 'Master Slave' : 'DataBase/MySQL/master-slave.md'
  - DevOps:
    - Docker:
      - 'Basic' : 'DevOps/docker.md'
  - About:
    - 'Who Am I': 'about.md'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    font: 'false'
  features:
    - tabs
  #collapse_navigation: true
  highlightjs: true

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.codehilite:
      guess_lang: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
